const SERVER_URL=window.GAME_SERVER_URL||"http://localhost:3000";
const state={screen:"home",playerName:"Player",roomCode:"",roomId:"",players:[],winningScore:6,socket:null,hand:[["J","♠"],["9","♠"],["A","♥"],["10","♥"],["K","♦"],["Q","♦"],["8","♣"],["7","♣"]],trick:[],turn:true,scoreA:0,scoreB:0,currentBid:15,trump:"—",history:[],chat:[],unread:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function showScreen(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id)?.classList.add("active");state.screen=id}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(window._t);window._t=setTimeout(()=>e.classList.remove("show"),1800)}
function code(){const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:5},()=>c[Math.floor(Math.random()*c.length)]).join("")}
function send(ev,data){if(state.socket?.connected){state.socket.emit(ev,data);return true}return false}
function renderLobby(){$("#lobbyCode").textContent=state.roomCode||"-----";$("#shareCode").textContent=state.roomCode||"-----";$("#playerCount").textContent=`${state.players.length} / 4 players`;$("#playersGrid").innerHTML=state.players.map((p,i)=>`<div class="player-card"><div class="avatar">${esc((p.name||"?")[0].toUpperCase())}</div><div><strong>${esc(p.name||"Player")} ${p.host?"👑":""}</strong><small>Team ${i%2?"B":"A"}</small></div><span class="status">${p.connected===false?"● Offline":"● Connected"}</span></div>`).join("");$("#startGame").disabled=state.players.length!==4;$("#startGame").style.opacity=state.players.length!==4?".45":"1"}
function renderGame(){$("#scoreA").textContent=state.scoreA;$("#scoreB").textContent=state.scoreB;$("#currentBid").textContent=state.currentBid;$("#trumpText").textContent=`TRUMP — ${state.trump}`;$("#turnPill").textContent=state.turn?"YOUR TURN":"WAITING FOR PLAYERS";$("#handHint").textContent=state.turn?"Choose a card to play":"Waiting for your turn";$("#hand").innerHTML=state.hand.map((c,i)=>`<button class="playing-card playable ${["♥","♦"].includes(c[1])?"red":""}" data-i="${i}"><span class="rank">${c[0]}</span><span class="suit">${c[1]}</span><span class="mini-rank">${c[0]}${c[1]}</span></button>`).join("");$$(".playing-card").forEach(b=>b.onclick=()=>play(+b.dataset.i));$("#trickCards").innerHTML=state.trick.length?state.trick.map(x=>{let c=x.card||x;return `<div class="trick-card ${["♥","♦"].includes(c[1])?"red":""}">${c[0]}${c[1]}</div>`}).join(""):`<div class="empty-trick">Waiting for cards</div>`;$("#history").innerHTML=state.history.map(x=>`<p>${esc(x)}</p>`).join("")}
function play(i){if(!state.turn)return toast("Wait for your turn.");if(!send("game:playCard",{roomId:state.roomId,index:i})){state.hand.splice(i,1);state.turn=false;renderGame();toast("Move shown locally")}}
function renderChat(){$("#chatMessages").innerHTML=state.chat.slice(-80).map(m=>`<div class="chat-message ${m.name===state.playerName?"mine":""}"><div class="meta">${esc(m.name)} · ${esc(m.time||"now")}</div><div class="bubble">${esc(m.text)}</div></div>`).join("");$("#chatMessages").scrollTop=$("#chatMessages").scrollHeight;$("#chatBadge").textContent=state.unread}
function connect(){if(!window.io)return;state.socket=io(SERVER_URL,{transports:["websocket","polling"]});state.socket.on("connect",()=>toast("Realtime server connected"));state.socket.on("disconnect",()=>toast("Realtime connection lost"));state.socket.on("room:state",x=>{state.roomId=x.roomId||state.roomId;state.roomCode=x.roomCode||state.roomCode;state.players=x.players||[];renderLobby();if(x.phase==="playing")showScreen("game")});state.socket.on("game:state",g=>{Object.assign(state,{scoreA:g.scoreA??state.scoreA,scoreB:g.scoreB??state.scoreB,currentBid:g.currentBid??state.currentBid,trump:g.trump??state.trump,trick:g.trick??state.trick,history:g.history??state.history,turn:!!g.turn});if(g.hand)state.hand=g.hand;renderGame()});state.socket.on("chat:message",m=>{state.chat.push(m);if(!$("#chatPanel").classList.contains("open")&&m.name!==state.playerName)state.unread++;renderChat()});state.socket.on("system:message",m=>toast(m.text||m))}
$$("[data-screen]").forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$("#createBtn").onclick=()=>showScreen("create");$("#joinBtn").onclick=()=>showScreen("join");
$("#confirmCreate").onclick=()=>{state.playerName=$("#createName").value.trim()||"Player";state.roomCode=code();state.winningScore=+$("#winningScore").value;showScreen("lobby");if(!send("room:create",{roomCode:state.roomCode,name:state.playerName,winningScore:state.winningScore})){state.players=[{name:state.playerName,host:true,connected:true}];renderLobby();toast("Local prototype room created")}};
$("#confirmJoin").onclick=()=>{state.playerName=$("#joinName").value.trim()||"Player";state.roomCode=$("#roomCode").value.trim().toUpperCase();if(state.roomCode.length<5)return toast("Enter a valid room code.");showScreen("lobby");if(!send("room:join",{roomCode:state.roomCode,name:state.playerName})){state.players=[{name:"Host",host:true},{name:state.playerName},{name:"Player 3"},{name:"Player 4"}];renderLobby();toast("Local prototype room joined")}};
$("#copyCode").onclick=async()=>{try{await navigator.clipboard.writeText(state.roomCode);toast("Room code copied")}catch{toast(state.roomCode)}};$("#shareBtn").onclick=async()=>{const text=`Join my Twenty-Nine room: ${state.roomCode}`;if(navigator.share){try{await navigator.share({title:"Twenty-Nine",text})}catch{}}else{try{await navigator.clipboard.writeText(text);toast("Invite copied")}catch{toast(text)}}};
$("#startGame").onclick=()=>{if(state.players.length!==4)return toast("Need 4 players.");if(send("room:start",{roomId:state.roomId})){showScreen("game");return}showScreen("game");renderGame()};
$("#infoBtn").onclick=()=>$("#gameDrawer").classList.add("open");$("#closeInfo").onclick=()=>$("#gameDrawer").classList.remove("open");$("#leaveGame").onclick=()=>showScreen("home");
$("#chatFab").onclick=()=>{$("#chatPanel").classList.add("open");state.unread=0;renderChat();$("#chatInput").focus()};$("#closeChat").onclick=()=>$("#chatPanel").classList.remove("open");
$("#chatForm").onsubmit=e=>{e.preventDefault();const i=$("#chatInput"),text=i.value.trim();if(!text)return;const m={roomId:state.roomId,name:state.playerName,text:text.slice(0,160),time:new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})};if(!send("chat:send",m)){state.chat.push(m);renderChat()}i.value=""};
$("#passBid").onclick=()=>{if(send("game:bid",{roomId:state.roomId,pass:true})){$("#bidModal").classList.add("hidden");return}$("#bidModal").classList.add("hidden");$("#trumpModal").classList.remove("hidden")};
$$(".suit-btn").forEach(b=>b.onclick=()=>{const suit=b.dataset.suit;if(send("game:trump",{roomId:state.roomId,suit})){$("#trumpModal").classList.add("hidden");return}state.trump=suit;$("#trumpModal").classList.add("hidden");renderGame()});
connect();renderGame();renderChat();
