const SERVER_URL="https://cards-29-server-1.onrender.com";
const state={socket:null,name:"",roomCode:"",roomId:"",room:null,game:null,chat:[],unread:0};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove("show"),1900)}
function screen(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id)?.classList.add("active")}
function emit(ev,data){if(!state.socket?.connected){toast("Not connected to game server");return false}state.socket.emit(ev,data);return true}
function setConnection(on){$("#connectionDot").className="dot "+(on?"on":"offline");$("#connectionText").textContent=on?"Connected":"Offline"}
function initials(n){return (n||"?").slice(0,1).toUpperCase()}
function connect(){if(!window.io)return toast("Socket library failed to load");state.socket=io(SERVER_URL,{transports:["websocket","polling"],reconnection:true});state.socket.on("connect",()=>{setConnection(true);if(state.roomCode&&state.name)emit("session:resume",{roomCode:state.roomCode,name:state.name})});state.socket.on("disconnect",()=>setConnection(false));state.socket.on("connect_error",()=>setConnection(false));
state.socket.on("error:message",m=>toast(m.text||"Something went wrong"));
state.socket.on("room:state",r=>{state.room=r;state.roomId=r.roomId;state.roomCode=r.roomCode;$("#lobbyCode").textContent=r.roomCode;$("#shareCode").textContent=r.roomCode;$("#playerCount").textContent=`${r.players.length} / 4 players`;$("#startGame").disabled=!r.canStart;$("#startGame").style.opacity=r.canStart?"1":".45";$("#playersGrid").innerHTML=r.players.map(p=>`<div class="player"><div class="avatar">${initials(p.name)}</div><div><b>${esc(p.name)} ${p.host?"👑":""}</b><small>Seat ${p.seat} · Team ${p.team}</small></div><span class="status">${p.connected?"● Connected":"● Reconnecting"}</span></div>`).join("");if(r.phase==="lobby")screen("lobby")});
state.socket.on("game:state",g=>{state.game=g;screen("game");renderGame();if(g.myTurn&&g.phase==="bidding")openBid();else close("bidModal");if(g.myTurn&&g.phase==="trump"&&g.bidderId===g.me)openTrump();else if(g.phase!=="trump")close("trumpModal")});
state.socket.on("chat:message",m=>{state.chat.push(m);if(!$("#chatPanel").classList.contains("open")&&m.name!==state.name){state.unread++;$("#chatBadge").textContent=state.unread}renderChat()});
state.socket.on("hand:result",r=>{close("bidModal");close("trumpModal");$("#resultTitle").textContent=r.success?"Bid made!":"Bid failed";$("#resultText").textContent=r.message;$("#resultA").textContent=r.scoreA;$("#resultB").textContent=r.scoreB;$("#handResult").classList.remove("hidden")});
state.socket.on("match:result",r=>{$("#winnerTitle").textContent=`🏆 ${r.winner} wins`;$("#winnerText").textContent=r.message;$("#matchResult").classList.remove("hidden")});
state.socket.on("system:message",m=>toast(m.text||m))}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function cardHTML(c,i,legal){return `<button class="card ${["♥","♦"].includes(c.suit)?"red":""}" data-i="${i}" ${legal?"":"disabled"}><span class="tiny">${c.rank}${c.suit}</span><span class="big">${c.suit}</span></button>`}
function renderGame(){const g=state.game;if(!g)return;$("#scoreA").textContent=g.scoreA;$("#scoreB").textContent=g.scoreB;$("#targetScore").textContent=g.target;$("#targetScoreB").textContent=g.target;$("#phaseText").textContent=g.phase==="bidding"?"BIDDING":g.phase==="trump"?"TRUMP SELECTION":g.phase==="playing"?"PLAYING":"HAND COMPLETE";$("#roundText").textContent=`Hand ${g.handNumber} · Trick ${g.trickNumber} / 8`;
$("#turnPill").textContent=g.myTurn?"YOUR TURN":(g.phase==="bidding"?"WAITING FOR BID":g.phase==="trump"?"WAITING FOR TRUMP":"WAITING");$("#trumpPill").textContent=g.trumpRevealed?`TRUMP — ${g.trump}`:"TRUMP — HIDDEN";$("#bidValue").textContent=g.bid||"—";$("#bidderValue").textContent=g.bidderName?`Bid by ${esc(g.bidderName)}`:"No bid yet";
const seatMap=g.seats||[];const top=seatMap.find(x=>x.position==="top"),left=seatMap.find(x=>x.position==="left"),right=seatMap.find(x=>x.position==="right");[[top,"top"],[left,"left"],[right,"right"]].forEach(([p,pos])=>{if(!p)return;$("#"+pos+"Avatar").textContent=initials(p.name);$("#"+pos+"Name").textContent=p.name;$("#"+pos+"Info").textContent=`Seat ${p.seat} · Team ${p.team} · ${p.cards} cards`});
$("#trick").innerHTML=g.trick?.length?g.trick.map(t=>`<div class="trick-card ${["♥","♦"].includes(t.card.suit)?"red":""}">${t.card.rank}${t.card.suit}</div>`).join(""):'<span class="empty">No cards in trick</span>';
$("#handHint").textContent=g.phase==="playing"?(g.myTurn?"Choose a legal card":"Waiting for your turn"):g.phase==="bidding"?(g.myTurn?"Choose a bid or pass":"Waiting for bids"):g.phase==="trump"?(g.myTurn?"Choose trump":"Bidder choosing trump"):"Waiting…";
$("#hand").innerHTML=(g.hand||[]).map((c,i)=>cardHTML(c,i,g.legalIndexes?.includes(i))).join("");$$(".card").forEach(b=>b.onclick=()=>emit("game:playCard",{roomId:state.roomId,index:+b.dataset.i}));
$("#infoTrump").textContent=g.trumpRevealed?g.trump:"Hidden";$("#infoBid").textContent=g.bid||"—";$("#infoTricks").textContent=`${g.tricksCompleted} / 8`;$("#history").innerHTML=(g.history||[]).map(x=>`<p>${esc(x)}</p>`).join("")}
function openBid(){const g=state.game;$("#modalBid").textContent=g.bid||15;$("#modalMin").textContent=Math.max(16,(g.bid||15)+1);const min=Math.max(16,(g.bid||15)+1);$("#bidGrid").innerHTML=Array.from({length:28-min+1},(_,k)=>{const n=min+k;return `<button data-bid="${n}">${n}</button>`}).join("");$$("[data-bid]").forEach(b=>b.onclick=()=>{emit("game:bid",{roomId:state.roomId,bid:+b.dataset.bid});close("bidModal")});$("#bidModal").classList.remove("hidden")}
function openTrump(){$("#trumpModal").classList.remove("hidden");$("#peekResult").textContent=""}
function close(id){$("#"+id)?.classList.add("hidden")}
function renderChat(){$("#chatMessages").innerHTML=state.chat.slice(-80).map(m=>`<div class="msg ${m.name===state.name?"mine":""}"><small>${esc(m.name)} · ${esc(m.time||"")}</small><p>${esc(m.text)}</p></div>`).join("");const e=$("#chatMessages");e.scrollTop=e.scrollHeight}
$$("[data-screen]").forEach(b=>b.onclick=()=>screen(b.dataset.screen));$("#createBtn").onclick=()=>screen("create");$("#joinBtn").onclick=()=>screen("join");
$("#confirmCreate").onclick=()=>{state.name=$("#createName").value.trim()||"Player";const target=+$("#winningScore").value;if(!state.socket?.connected)return toast("Wait for server connection");emit("room:create",{name:state.name,target})};
$("#confirmJoin").onclick=()=>{state.name=$("#joinName").value.trim()||"Player";state.roomCode=$("#joinCode").value.trim().toUpperCase();if(state.roomCode.length!==5)return toast("Room code must be 5 characters");emit("room:join",{roomCode:state.roomCode,name:state.name})};
$("#copyCode").onclick=async()=>{try{await navigator.clipboard.writeText(state.roomCode);toast("Room code copied")}catch{toast(state.roomCode)}};$("#shareBtn").onclick=async()=>{const text=`Join my Twenty-Nine room: ${state.roomCode}`;try{if(navigator.share)await navigator.share({title:"Twenty-Nine",text});else{await navigator.clipboard.writeText(text);toast("Invite copied")}}catch{}};
$("#startGame").onclick=()=>emit("room:start",{roomId:state.roomId});$("#passBtn").onclick=()=>{emit("game:bid",{roomId:state.roomId,pass:true});close("bidModal")};
$$(".suits button").forEach(b=>b.onclick=()=>{emit("game:trump",{roomId:state.roomId,suit:b.dataset.suit});close("trumpModal")});
$("#peekBtn").onclick=()=>emit("game:peek7",{roomId:state.roomId});$("#nextHandBtn").onclick=()=>{close("handResult");emit("hand:continue",{roomId:state.roomId})};$("#backLobbyBtn").onclick=()=>{close("matchResult");screen("lobby")};
$("#chatFab").onclick=()=>{$("#chatPanel").classList.add("open");state.unread=0;$("#chatBadge").textContent=0;$("#chatInput").focus();renderChat()};$("#closeChat").onclick=()=>$("#chatPanel").classList.remove("open");
$("#chatForm").onsubmit=e=>{e.preventDefault();const input=$("#chatInput"),text=input.value.trim();if(!text)return;emit("chat:send",{roomId:state.roomId,text:text.slice(0,160)});input.value=""};
$("#infoBtn").onclick=()=>$("#infoPanel").classList.add("open");$("#closeInfo").onclick=()=>$("#infoPanel").classList.remove("open");
connect();
function loadSaved(){const s=JSON.parse(localStorage.getItem("twentyNineSession")||"null");if(s){state.name=s.name||"";state.roomCode=s.roomCode||""}}loadSaved();
setInterval(()=>{if(state.roomCode&&state.name)localStorage.setItem("twentyNineSession",JSON.stringify({name:state.name,roomCode:state.roomCode}))},1000);
